apiVersion: apps/v1
kind: Deployment
metadata: { name: backend }
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
      - name: backend
        image: mern-backend:dev
        imagePullPolicy: IfNotPresent
        env:
        - { name: NODE_ENV, value: "production" }
        - { name: PORT,     value: "5000" }
        - { name: MONGO_URI, value: "mongodb://admin:pass@mongo:27017/mern?authSource=admin" }
        - { name: ATLAS_URI, value: "mongodb://admin:pass@mongo:27017/mern?authSource=admin" }
        ports: [ { containerPort: 5000 } ]